#ifndef JOS_INC_TRAP_H
#define JOS_INC_TRAP_H

// Trap numbers
// 这些都是处理器定义的
#define T_DIVIDE		0		// 除法错误
#define T_DEBUG		1		// 调试异常
#define T_NMI		2		// 不可屏蔽中断
#define T_BRKPT		3		// 断点
#define T_OFLOW		4		// 溢出
#define T_BOUND		5		// 边界检查
#define T_ILLOP		6		// 非法操作码
#define T_DEVICE		7		// 设备不可用
#define T_DBLFLT		8		// 双重故障
/* #define T_COPROC  9 */		// reserved (not generated by recent processors)
#define T_TSS		10		// 无效的任务切换段
#define T_SEGNP		11		// 段不存在
#define T_STACK		12		// 栈异常
#define T_GPFLT		13		// 一般保护故障
#define T_PGFLT		14		// 页面错误
/* #define T_RES    15 */		// reserved
#define T_FPERR		16		// 浮点指针错误
#define T_ALIGN		17		// 对齐检查
#define T_MCHK		18		// 机器检查
#define T_SIMDERR	19		// SIMD 浮点指针错误

// 这些是任意选择的，但小心不要重叠处理器定义的异常或中断向量.
#define T_SYSCALL	48		// system call
#define T_DEFAULT	500		// catchall

#define IRQ_OFFSET	32		// IRQ 0 corresponds to int IRQ_OFFSET

// 硬件IRQ编号. We receive these as (IRQ_OFFSET+IRQ_WHATEVER)
#define IRQ_TIMER		0
#define IRQ_KBD			1
#define IRQ_SERIAL		4
#define IRQ_SPURIOUS		7
#define IRQ_IDE			14
#define IRQ_ERROR		19

#ifndef __ASSEMBLER__

#include <inc/types.h>

struct PushRegs {
	uint32_t reg_edi;
	uint32_t reg_esi;
	uint32_t reg_ebp;
	uint32_t reg_oesp;		// 几乎不用
	uint32_t reg_ebx;
	uint32_t reg_edx;
	uint32_t reg_ecx;
	uint32_t reg_eax;
} __attribute__((packed));

struct Trapframe {
	struct PushRegs tf_regs;
	uint16_t tf_es;
	uint16_t tf_padding1;
	uint16_t tf_ds;
	uint16_t tf_padding2;
	uint32_t tf_trapno;
	// 以下是 x86 硬件定义的
	uint32_t tf_err;
	uintptr_t tf_eip;
	uint16_t tf_cs;
	uint16_t tf_padding3;
	uint32_t tf_eflags;
	// 以下是仅当模式切换时，如从用户到内核 才用到
	uintptr_t tf_esp;
	uint16_t tf_ss;
	uint16_t tf_padding4;
}__attribute__((packed));

#endif /* !__ASSEMBLER__ */

#endif /* !JOS_INC_TRAP_H */
